export interface GalleryItem {
  id: string
  src: string
  alt: string
  title: string
  description: string
  year: '2013' | '2014' | '2016' | '2017' | '2026'
  category: 'Conference' | 'Exhibition' | 'Gala Dinner' | 'Networking'
}

export const GALLERY_YEARS = ['All', '2026', '2017', '2016', '2014', '2013'] as const;
export const GALLERY_CATEGORIES = ['All', 'Conference', 'Exhibition', 'Gala Dinner', 'Networking'] as const;

export const HISTORICAL_GALLERY_ITEMS: GalleryItem[] = [
  // -------------------------------------------------------------
  // 2017 GALLERY ITEMS (High-resolution Summit Coverage)
  // -------------------------------------------------------------
  {
    id: '2017-0001',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0001.jpg',
    alt: 'NBAC 2017 Opening Plenary Session',
    title: 'Opening Plenary Session',
    description: 'Welcome address and opening remarks at the 2017 Nigerian Business Aviation Conference.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0002',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0002.jpg',
    alt: 'NBAC 2017 Keynote Presentation',
    title: 'Keynote Leadership Address',
    description: 'Industry leaders sharing insights on regional business aviation infrastructure.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0003',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0003.jpg',
    alt: 'NBAC 2017 Executive Audience',
    title: 'Delegates & Stakeholders',
    description: 'C-suite aviation executives and policy makers attending the opening sessions.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0004',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0004.jpg',
    alt: 'NBAC 2017 Industry Panel Discussion',
    title: 'Regulatory & Policy Forum',
    description: 'Panelists discussing West African airspace access, tax policies, and cross-border flight approvals.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0005',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0005.jpg',
    alt: 'NBAC 2017 Delegate Q&A',
    title: 'Interactive Forum Debate',
    description: 'Audience Q&A addressing aircraft registration and maintenance standards.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0006',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0006.jpg',
    alt: 'NBAC 2017 Exhibition Pavilion',
    title: 'Exhibition Hall Walkthrough',
    description: 'Delegates touring partner booths and manufacturer displays in the main hall.',
    year: '2017',
    category: 'Exhibition',
  },
  {
    id: '2017-0007',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0007.jpg',
    alt: 'NBAC 2017 OEM Display Booth',
    title: 'Aircraft Manufacturer Showcase',
    description: 'Leading global OEMs highlighting the latest business aircraft models.',
    year: '2017',
    category: 'Exhibition',
  },
  {
    id: '2017-0008',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0008.jpg',
    alt: 'NBAC 2017 Networking Coffee Break',
    title: 'Executive Networking Break',
    description: 'B2B interactions during the mid-morning networking tea break.',
    year: '2017',
    category: 'Networking',
  },
  {
    id: '2017-0009',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0009.jpg',
    alt: 'NBAC 2017 B2B Discussions',
    title: 'B2B Operator Meetings',
    description: 'Charter operators and aircraft brokers discussing fleet management partnerships.',
    year: '2017',
    category: 'Networking',
  },
  {
    id: '2017-0010',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0010.jpg',
    alt: 'NBAC 2017 FBO Services Showcase',
    title: 'FBO & Ground Handling Showcase',
    description: 'Showcasing VIP passenger handling and ramp support capabilities in Lagos.',
    year: '2017',
    category: 'Exhibition',
  },
  {
    id: '2017-0011',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0011.jpg',
    alt: 'NBAC 2017 Afternoon Panel',
    title: 'Aircraft Financing & Leasing',
    description: 'Financial experts sharing strategies for cross-border jet acquisitions in West Africa.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0012',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0012.jpg',
    alt: 'NBAC 2017 Safety & Maintenance Session',
    title: 'Safety Standards & AMO Focus',
    description: 'Technical presentation on NCAA maintenance standards and safety audits.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0013',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0013.jpg',
    alt: 'NBAC 2017 Static Display Line',
    title: 'Static Aircraft Display',
    description: 'Delegates examining modern turboprops and business jets on the airfield.',
    year: '2017',
    category: 'Exhibition',
  },
  {
    id: '2017-0014',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0014.jpg',
    alt: 'NBAC 2017 VIP Lounge Experience',
    title: 'VIP Lounge Reception',
    description: 'Private lounge networking for VIP guests and sponsor delegations.',
    year: '2017',
    category: 'Networking',
  },
  {
    id: '2017-0015',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0015.jpg',
    alt: 'NBAC 2017 Technology & Avionics Booth',
    title: 'Avionics & Tech Innovations',
    description: 'Demonstrations of state-of-the-art flight deck avionics and satellite communications.',
    year: '2017',
    category: 'Exhibition',
  },
  {
    id: '2017-0016',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0016.jpg',
    alt: 'NBAC 2017 Press & Media Briefing',
    title: 'Media Briefing & Announcements',
    description: 'Press conference highlighting key regional aviation milestones and partnerships.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0017',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0017.jpg',
    alt: 'NBAC 2017 Evening Reception',
    title: 'Evening Networking Reception',
    description: 'An informal evening gathering connecting international delegates.',
    year: '2017',
    category: 'Networking',
  },
  {
    id: '2017-0018',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0018.jpg',
    alt: 'NBAC 2017 Gala Banquet Dinner',
    title: 'An Evening of Aviators Gala',
    description: 'The signature gala dinner celebrating the culmination of the 2017 summit.',
    year: '2017',
    category: 'Gala Dinner',
  },
  {
    id: '2017-0019',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0019.jpg',
    alt: 'NBAC 2017 Awards Ceremony',
    title: 'Business Aviation Awards',
    description: 'Recognizing outstanding contributions to West African business aviation.',
    year: '2017',
    category: 'Gala Dinner',
  },
  {
    id: '2017-0020',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0020.jpg',
    alt: 'NBAC 2017 Gala Toast',
    title: 'Closing Toast & Celebrations',
    description: 'Delegates and dignitaries raising a toast to industry growth and collaboration.',
    year: '2017',
    category: 'Gala Dinner',
  },
  {
    id: '2017-0021',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0021.jpg',
    alt: 'NBAC 2017 Delegate Networking Hall',
    title: 'Summit Exhibition Hall',
    description: 'High-energy discussions across the main conference floor.',
    year: '2017',
    category: 'Exhibition',
  },
  {
    id: '2017-0022',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0022.jpg',
    alt: 'NBAC 2017 Leadership Roundtable',
    title: 'Executive Roundtable Discussions',
    description: 'Focused roundtables on fleet optimization and charter demand.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0023',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0023.jpg',
    alt: 'NBAC 2017 Helicopter Operations',
    title: 'Helicopter & Rotary Services Showcase',
    description: 'Focus session on offshore rotary transport and VIP helicopter charter.',
    year: '2017',
    category: 'Exhibition',
  },
  {
    id: '2017-0024',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0024.jpg',
    alt: 'NBAC 2017 Catering & Hospitality',
    title: 'In-Flight Catering Experience',
    description: 'Exhibition of gourmet culinary offerings designed for corporate aircraft.',
    year: '2017',
    category: 'Exhibition',
  },
  {
    id: '2017-0025',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0025.jpg',
    alt: 'NBAC 2017 Delegate Interactions',
    title: 'Stakeholder Alliance Building',
    description: 'Connecting international suppliers with local operational leads.',
    year: '2017',
    category: 'Networking',
  },
  {
    id: '2017-0026',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0026.jpg',
    alt: 'NBAC 2017 Plenary Auditorium',
    title: 'Main Hall Keynote',
    description: 'Panoramic view of the packed main auditorium during the summit.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0027',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0027.jpg',
    alt: 'NBAC 2017 Aviation Security Forum',
    title: 'Aviation Security & Compliance',
    description: 'Experts sharing insights on VIP security protocols and international compliance.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0028',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0028.jpg',
    alt: 'NBAC 2017 Sponsor Recognition',
    title: 'Sponsor Recognition Ceremony',
    description: 'Honoring key global sponsors and strategic corporate partners.',
    year: '2017',
    category: 'Gala Dinner',
  },
  {
    id: '2017-0030',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0030.jpg',
    alt: 'NBAC 2017 Interactive Workshop',
    title: 'Technical Flight Ops Workshop',
    description: 'Operational workshop covering flight planning, dispatch, and weather management.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0038',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0038.jpg',
    alt: 'NBAC 2017 Executive Luncheon',
    title: 'Summit VIP Luncheon',
    description: 'Executive lunch break facilitating high-level networking.',
    year: '2017',
    category: 'Networking',
  },
  {
    id: '2017-0041',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0041.jpg',
    alt: 'NBAC 2017 Hangar Facility Tour',
    title: 'Hangar Facilities Showcase',
    description: 'Exclusive tour of EAN Aviation hangar infrastructure and maintenance bays.',
    year: '2017',
    category: 'Exhibition',
  },
  {
    id: '2017-0051',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0051.jpg',
    alt: 'NBAC 2017 Commercial Flight Forum',
    title: 'Regional Sky Growth Debate',
    description: 'Panel addressing cross-border air connectivity across ECOWAS sub-region.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0054',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0054.jpg',
    alt: 'NBAC 2017 Delegate Discussions',
    title: 'Delegates Lounge Exchange',
    description: 'Industry professionals sharing operational best practices.',
    year: '2017',
    category: 'Networking',
  },
  {
    id: '2017-0061',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0061.jpg',
    alt: 'NBAC 2017 Innovation Hub',
    title: 'Aviation Software & Digital Tech',
    description: 'Demonstrations of modern dispatch and automated flight tracking systems.',
    year: '2017',
    category: 'Exhibition',
  },
  {
    id: '2017-0062',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0062.jpg',
    alt: 'NBAC 2017 Regulators Exchange',
    title: 'Civil Aviation Regulatory Exchange',
    description: 'NCAA and international civil aviation representatives aligning on rules.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0073',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0073.jpg',
    alt: 'NBAC 2017 Closing Plenary',
    title: 'Closing Summit Resolutions',
    description: 'Presenting summit resolutions and key action items for the upcoming year.',
    year: '2017',
    category: 'Conference',
  },
  {
    id: '2017-0074',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0074.jpg',
    alt: 'NBAC 2017 Celebration Toast',
    title: 'Closing Ceremony Toast',
    description: 'Organizers and delegates celebrating a successful 2017 conference.',
    year: '2017',
    category: 'Gala Dinner',
  },
  {
    id: '2017-0075',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0075.jpg',
    alt: 'NBAC 2017 Evening Musical Performance',
    title: 'Gala Dinner Entertainment',
    description: 'Live musical performances and cultural entertainment during the gala.',
    year: '2017',
    category: 'Gala Dinner',
  },
  {
    id: '2017-0080',
    src: '/images/NBAC/2017/AfRS_NBAC17_Day1_0080.jpg',
    alt: 'NBAC 2017 Farewell Reception',
    title: 'Farewell Delegate Reception',
    description: 'Final networking gathering concluding the 2017 summit activities.',
    year: '2017',
    category: 'Networking',
  },

  // -------------------------------------------------------------
  // 2016 GALLERY ITEMS (HD High-Resolution Summit Coverage)
  // -------------------------------------------------------------
  {
    id: '2016-2965',
    src: '/images/NBAC/2016/DSC_2965-1024x684.jpg',
    alt: 'NBAC 2016 Airspace Policy Forum',
    title: 'Advocating for Sky Openness',
    description: 'Advocacy sessions on tax incentives, customs, and airspace access rules.',
    year: '2016',
    category: 'Conference',
  },
  {
    id: '2016-3012',
    src: '/images/NBAC/2016/DSC_3012-1024x684.jpg',
    alt: 'NBAC 2016 Opening Plenary Session',
    title: 'Opening Leadership Keynote',
    description: 'Keynote presentation on business aviation infrastructure in Nigeria.',
    year: '2016',
    category: 'Conference',
  },
  {
    id: '2016-3100',
    src: '/images/NBAC/2016/DSC_3100-1024x684.jpg',
    alt: 'NBAC 2016 Regulatory Forum',
    title: 'Regulatory & Policy Roundtable',
    description: 'Aligning CAA and local operators on maintenance standards.',
    year: '2016',
    category: 'Conference',
  },
  {
    id: '2016-3133',
    src: '/images/NBAC/2016/DSC_3133-1024x684.jpg',
    alt: 'NBAC 2016 Exhibition Hall',
    title: '2016 Exhibition Floor',
    description: 'Manufacturers and OEMs showcasing modern aircraft technology.',
    year: '2016',
    category: 'Exhibition',
  },
  {
    id: '2016-3174',
    src: '/images/NBAC/2016/DSC_3174-1024x684.jpg',
    alt: 'NBAC 2016 OEM Display',
    title: 'Business Aircraft Showcase',
    description: 'Exploring state-of-the-art corporate turboprops and jets.',
    year: '2016',
    category: 'Exhibition',
  },
  {
    id: '2016-3182',
    src: '/images/NBAC/2016/DSC_3182-1024x684.jpg',
    alt: 'NBAC 2016 Technical Presentation',
    title: 'Avionics & Flight Operations',
    description: 'Technical session detailing flight dispatch tools and avionics.',
    year: '2016',
    category: 'Conference',
  },
  {
    id: '2016-3274',
    src: '/images/NBAC/2016/DSC_3274-1024x684.jpg',
    alt: 'NBAC 2016 Executive Networking',
    title: 'Coffee Break Connections',
    description: 'Executive networking between morning plenary sessions.',
    year: '2016',
    category: 'Networking',
  },
  {
    id: '2016-3328',
    src: '/images/NBAC/2016/DSC_3328-1024x684.jpg',
    alt: 'NBAC 2016 B2B Consultations',
    title: 'Charter & Fleet Consultations',
    description: 'Connecting international brokers with West African flight departments.',
    year: '2016',
    category: 'Networking',
  },
  {
    id: '2016-3344',
    src: '/images/NBAC/2016/DSC_3344-1024x684.jpg',
    alt: 'NBAC 2016 Hangar Tour',
    title: 'Hangar Facilities Visit',
    description: 'Delegates touring EAN Aviation hangar infrastructure and maintenance bays.',
    year: '2016',
    category: 'Exhibition',
  },
  {
    id: '2016-3413',
    src: '/images/NBAC/2016/DSC_3413-1024x684.jpg',
    alt: 'NBAC 2016 Static Display',
    title: 'Airfield Static Jet Display',
    description: 'Executive aircraft on display at the FBO ramp.',
    year: '2016',
    category: 'Exhibition',
  },
  {
    id: '2016-3420',
    src: '/images/NBAC/2016/DSC_3420-1024x684.jpg',
    alt: 'NBAC 2016 Ramp Inspection',
    title: 'VIP Aircraft Cabin Tour',
    description: 'Inspecting custom corporate cabin interiors.',
    year: '2016',
    category: 'Exhibition',
  },
  {
    id: '2016-3913',
    src: '/images/NBAC/2016/DSC_3913-1024x684.jpg',
    alt: 'NBAC 2016 Afternoon Panel',
    title: 'Aircraft Finance Forum',
    description: 'Strategies for financing corporate jets in West Africa.',
    year: '2016',
    category: 'Conference',
  },
  {
    id: '2016-3938',
    src: '/images/NBAC/2016/DSC_3938-1024x684.jpg',
    alt: 'NBAC 2016 Gala Evening',
    title: '2016 Gala Dinner Reception',
    description: 'Evening banquet connecting international delegates.',
    year: '2016',
    category: 'Gala Dinner',
  },
  {
    id: '2016-3946',
    src: '/images/NBAC/2016/DSC_3946-1024x684.jpg',
    alt: 'NBAC 2016 Gala Celebration',
    title: 'Gala Evening Celebrations',
    description: 'Honoring industry achievements during the gala banquet.',
    year: '2016',
    category: 'Gala Dinner',
  },
  {
    id: '2016-4036',
    src: '/images/NBAC/2016/DSC_4036-1024x684.jpg',
    alt: 'NBAC 2016 Awards Toast',
    title: 'Industry Leadership Awards',
    description: 'Recognizing outstanding contributions to West African business aviation.',
    year: '2016',
    category: 'Gala Dinner',
  },
  {
    id: '2016-4070',
    src: '/images/NBAC/2016/DSC_4070-1024x684.jpg',
    alt: 'NBAC 2016 Closing Reception',
    title: 'Summit Closing Toast',
    description: 'Closing remarks and toast concluding the 2016 summit.',
    year: '2016',
    category: 'Gala Dinner',
  },
  {
    id: '2016-3388',
    src: '/images/NBAC/2016/IMG_3388-1024x682.jpg',
    alt: 'NBAC 2016 Delegates Group',
    title: '2016 Delegate Assembly',
    description: 'Delegates and organizers gathered for the 2016 summit photo.',
    year: '2016',
    category: 'Networking',
  },

  // -------------------------------------------------------------
  // 2014 GALLERY ITEMS (HD High-Resolution Coverage)
  // -------------------------------------------------------------
  {
    id: '2014-conf-48',
    src: '/images/NBAC/2014/Conference-48-1024x683.jpg',
    alt: 'NBAC 2014 Regulatory Harmonization Session',
    title: 'Regulatory Harmonization Session',
    description: 'Panelists evaluating regulatory challenges for West African business jets.',
    year: '2014',
    category: 'Conference',
  },
  {
    id: '2014-embraer-dinner',
    src: '/images/NBAC/2014/Ebraer-Dinner-175-1024x683.jpg',
    alt: 'NBAC 2014 Embraer Sponsored Dinner',
    title: 'Embraer VIP Dinner Banquet',
    description: 'Exclusive evening banquet hosted by Embraer Executive Jets.',
    year: '2014',
    category: 'Gala Dinner',
  },
  {
    id: '2014-gulfstream-3',
    src: '/images/NBAC/2014/Gulfstream-Dinner-3-1024x683.jpg',
    alt: 'NBAC 2014 Gulfstream Executive Reception',
    title: 'Gulfstream Corporate Reception',
    description: 'VIP delegates gathered at the Gulfstream-hosted evening reception.',
    year: '2014',
    category: 'Gala Dinner',
  },
  {
    id: '2014-day1-256',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Day-1-256-of-465-1024x683.jpg',
    alt: 'NBAC 2014 Day 1 Delegate Plenary',
    title: 'Day 1 Plenary Assembly',
    description: 'Delegates gathered for the opening plenary session.',
    year: '2014',
    category: 'Conference',
  },
  {
    id: '2014-day1-303',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Day-1-303-of-465-1024x683.jpg',
    alt: 'NBAC 2014 Industry Presentation',
    title: 'Infrastructure Presentation',
    description: 'Keynote detailing business jet operations and airport growth.',
    year: '2014',
    category: 'Conference',
  },
  {
    id: '2014-day1-347',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Day-1-347-of-465-1024x683.jpg',
    alt: 'NBAC 2014 Day 1 Keynote Address',
    title: '2014 Summit Opening Keynote',
    description: 'Opening address detailing business aviation expansion in Nigeria.',
    year: '2014',
    category: 'Conference',
  },
  {
    id: '2014-day1-392',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Day-1-392-of-465-1024x683.jpg',
    alt: 'NBAC 2014 Plenary Audience',
    title: 'Delegate Plenary Session',
    description: 'Industry stakeholders participating in the 2014 plenary debates.',
    year: '2014',
    category: 'Conference',
  },
  {
    id: '2014-day1-401',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Day-1-401-of-465-1024x576 (1).jpg',
    alt: 'NBAC 2014 Infrastructure Forum',
    title: 'Infrastructure & FBO Growth Panel',
    description: 'Discussions on hangar capacity, fueling, and ground support services.',
    year: '2014',
    category: 'Conference',
  },
  {
    id: '2014-day2-268',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Day-2-268-of-323-1024x683 (1).jpg',
    alt: 'NBAC 2014 Technical Discussions',
    title: 'Flight Operations Forum',
    description: 'Technical and operational flight crew discussions.',
    year: '2014',
    category: 'Conference',
  },
  {
    id: '2014-day2-38',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Day-2-38-of-323-1024x683.jpg',
    alt: 'NBAC 2014 Morning Keynote',
    title: 'Day 2 Leadership Keynote',
    description: 'Focusing on flight crew training, safety management systems, and compliance.',
    year: '2014',
    category: 'Conference',
  },
  {
    id: '2014-day2-65',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Day-2-65-of-323-1024x683.jpg',
    alt: 'NBAC 2014 Technical Panel',
    title: 'Safety Standards Forum',
    description: 'Safety management and aviation regulatory alignment.',
    year: '2014',
    category: 'Conference',
  },
  {
    id: '2014-gala-161',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Gala-Dinner-161-of-323-1024x683 (1).jpg',
    alt: 'NBAC 2014 Gala Reception',
    title: 'Gala Evening Reception',
    description: 'Delegates gathering for the official summit closing dinner.',
    year: '2014',
    category: 'Gala Dinner',
  },
  {
    id: '2014-gala-190',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Gala-Dinner-190-of-323-1024x505.jpg',
    alt: 'NBAC 2014 Gala Dinner Banquet',
    title: 'Summit Closing Banquet',
    description: 'Executive banquet dinner celebrating conference achievements.',
    year: '2014',
    category: 'Gala Dinner',
  },
  {
    id: '2014-gala-256',
    src: '/images/NBAC/2014/NBAC-2014-Conference-Gala-Dinner-256-of-323-1024x683 (1).jpg',
    alt: 'NBAC 2014 Closing Awards & Banquet',
    title: 'Closing Awards & Celebration',
    description: 'Celebrating industry achievements during the closing banquet.',
    year: '2014',
    category: 'Gala Dinner',
  },

  // -------------------------------------------------------------
  // 2013 GALLERY ITEMS (HD High-Resolution Coverage)
  // -------------------------------------------------------------
  {
    id: '2013-7923',
    src: '/images/NBAC/2013/img_7923.jpg',
    alt: 'NBAC 2013 Opening Ceremony',
    title: 'Inaugural Summit Opening',
    description: 'Opening ceremony at the 2013 Nigerian Business Aviation Conference.',
    year: '2013',
    category: 'Conference',
  },
  {
    id: '2013-8089',
    src: '/images/NBAC/2013/img_8089.jpg',
    alt: 'NBAC 2013 Exhibition Pavilion',
    title: 'First Edition Exhibition',
    description: 'Pioneer exhibition display at the inaugural summit.',
    year: '2013',
    category: 'Exhibition',
  },
  {
    id: '2013-8112',
    src: '/images/NBAC/2013/img_8112.jpg',
    alt: 'NBAC 2013 Delegate Plenary',
    title: 'Inaugural Plenary Assembly',
    description: 'Founding delegates attending the plenary sessions.',
    year: '2013',
    category: 'Conference',
  },
  {
    id: '2013-8115',
    src: '/images/NBAC/2013/img_8115.jpg',
    alt: 'NBAC 2013 Keynote Presentation',
    title: 'Founding Leadership Keynote',
    description: 'Industry pioneers presenting vision for West African business flight.',
    year: '2013',
    category: 'Conference',
  },
  {
    id: '2013-8131',
    src: '/images/NBAC/2013/img_8131.jpg',
    alt: 'NBAC 2013 Coffee Networking',
    title: 'Delegate Networking Tea Break',
    description: 'Networking session between morning forum discussions.',
    year: '2013',
    category: 'Networking',
  },
  {
    id: '2013-8133',
    src: '/images/NBAC/2013/img_8133.jpg',
    alt: 'NBAC 2013 B2B Discussions',
    title: 'B2B Executive Discussions',
    description: 'High-level executive interactions during the 2013 summit.',
    year: '2013',
    category: 'Networking',
  },
  {
    id: '2013-8184',
    src: '/images/NBAC/2013/img_8184.jpg',
    alt: 'NBAC 2013 Technical Session',
    title: 'Flight Safety & Operations',
    description: 'Technical presentation on safety management and maintenance standards.',
    year: '2013',
    category: 'Conference',
  },
  {
    id: '2013-8288',
    src: '/images/NBAC/2013/img_8288.jpg',
    alt: 'NBAC 2013 Static Jet Display',
    title: 'Static Aircraft Display',
    description: 'Corporate business jets parked on the ramp during the 2013 summit.',
    year: '2013',
    category: 'Exhibition',
  },
  {
    id: '2013-8309',
    src: '/images/NBAC/2013/img_8309.jpg',
    alt: 'NBAC 2013 Ramp Walkthrough',
    title: 'FBO Ramp Tour',
    description: 'Delegates touring the static display line at Lagos airport.',
    year: '2013',
    category: 'Exhibition',
  },
  {
    id: '2013-8319',
    src: '/images/NBAC/2013/img_8319.jpg',
    alt: 'NBAC 2013 Aircraft Showcase',
    title: 'Turboprop & Jet Showcase',
    description: 'Exploring modern executive aircraft cabins and flight decks.',
    year: '2013',
    category: 'Exhibition',
  },
  {
    id: '2013-8337',
    src: '/images/NBAC/2013/img_8337.jpg',
    alt: 'NBAC 2013 Afternoon Forum',
    title: 'Regional Aviation Growth',
    description: 'Panelists deliberating on infrastructure and cross-border flight access.',
    year: '2013',
    category: 'Conference',
  },
  {
    id: '2013-8345',
    src: '/images/NBAC/2013/img_8345.jpg',
    alt: 'NBAC 2013 Operator Roundtable',
    title: 'Operator & Broker Roundtable',
    description: 'Charter operators aligning on operational fleet capacity.',
    year: '2013',
    category: 'Conference',
  },
  {
    id: '2013-8375',
    src: '/images/NBAC/2013/img_8375.jpg',
    alt: 'NBAC 2013 Supplier Pavilion',
    title: 'Aviation Equipment & Parts',
    description: 'Exhibition of flight planning software, avionics, and aircraft parts.',
    year: '2013',
    category: 'Exhibition',
  },
  {
    id: '2013-8393',
    src: '/images/NBAC/2013/img_8393.jpg',
    alt: 'NBAC 2013 Evening Reception',
    title: 'Cocktail Networking Reception',
    description: 'Informal evening networking connecting local and international delegates.',
    year: '2013',
    category: 'Networking',
  },
  {
    id: '2013-8405',
    src: '/images/NBAC/2013/img_8405.jpg',
    alt: 'NBAC 2013 Dinner Reception',
    title: 'Gala Evening Welcome',
    description: 'Welcome reception for the inaugural gala dinner banquet.',
    year: '2013',
    category: 'Gala Dinner',
  },
  {
    id: '2013-8417',
    src: '/images/NBAC/2013/img_8417.jpg',
    alt: 'NBAC 2013 Gala Dinner',
    title: 'Inaugural Gala Banquet',
    description: 'The inaugural gala dinner celebrating the launch of NBAC 2013.',
    year: '2013',
    category: 'Gala Dinner',
  },
  {
    id: '2013-8439',
    src: '/images/NBAC/2013/img_8439.jpg',
    alt: 'NBAC 2013 Celebration Toast',
    title: 'Closing Celebration Toast',
    description: 'Raising a toast to regional business aviation progress.',
    year: '2013',
    category: 'Gala Dinner',
  },
  {
    id: '2013-8446',
    src: '/images/NBAC/2013/img_8446.jpg',
    alt: 'NBAC 2013 Closing Ceremony',
    title: 'Inaugural Summit Concluding Photo',
    description: 'Commemorative group photo concluding the inaugural 2013 summit.',
    year: '2013',
    category: 'Networking',
  },
];
